sudo: false
language: python
python:
- '3.5'

install:
  - pip install git+https://github.com/OpenTrons/protocol-library.git#egg=340-create-travis-script-to-scan-through-protocols

script:
  - build-library .
