sudo: false
language: python
python:
- '3.5'

install:
  - echo $PATH
  - pip install -r protolib/requirements.txt
  - pip install flake8

script:
  - python --version
  - python3 --version
  - python -c 'import opentrons; print(opentrons.__version__)'
  # lint all protocols
  - flake8 .
  # - ./scripts/smoke-test.sh  # skip smoke testing, hope protolib catches it
  #
  # build zipped .json
  # - library-build . releases
  - python protolib/cli.py . releases/
  - ls -la releases/

# Deploy the build version in an S3 bucket
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: protocol-library-builds
  skip_cleanup: true
  local-dir: releases
  upload-dir: $OT_UPLOAD_BRANCH
  acl: private
  on:
    repo: Opentrons/Protocols
    all_branches: true

notifications:
  email:
    on_success: change
    on_failure: change
