sudo: false
language: python
python:
- '3.5'

install:
  - openssl aes-256-cbc -K $encrypted_43309740674a_key -iv $encrypted_43309740674a_iv -in .ci/protocol-library.enc -out ../protocol-library -d
  - chmod 600 ../protocol-library
  - eval `ssh-agent -s`
  - ssh-add ../protocol-library
  - pip install git+ssh://git@github.com/OpenTrons/protocol-library.git@340-create-travis-script-to-scan-through-protocols#egg=protolib
  - echo $PATH

script:
  - python --version
  - python3 --version
  - python -c 'import os; from protolib import build_protocol_library; build_protocol_library(os.getcwd())'
  - build-library .
  - echo $PATH
  - pip list
